//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessTrackerWebApp
{
    public partial class Nutrition
    {
        protected global::System.Web.UI.WebControls.TextBox txtId;
        protected global::System.Web.UI.WebControls.TextBox txtUserId;
        protected global::System.Web.UI.WebControls.TextBox txtFoodItem;
        protected global::System.Web.UI.WebControls.TextBox txtCalories;
        protected global::System.Web.UI.WebControls.TextBox txtDateConsumed;
        protected global::System.Web.UI.WebControls.GridView gvNutrition;
        protected global::System.Web.UI.WebControls.Button btnCreate;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Button btnDelete;
    }
}
