//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessTrackerWebApp
{
    public partial class Progress
    {
        protected global::System.Web.UI.WebControls.TextBox txtId;
        protected global::System.Web.UI.WebControls.TextBox txtUserId;
        protected global::System.Web.UI.WebControls.TextBox txtWeight;
        protected global::System.Web.UI.WebControls.TextBox txtBMI;
        protected global::System.Web.UI.WebControls.TextBox txtDateRecorded;
        protected global::System.Web.UI.WebControls.GridView gvProgress;
        protected global::System.Web.UI.WebControls.Button btnCreate;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.Button btnDelete;
    }
}
